name: Snyk Open Source Test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'main'

jobs:
  open-source-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            architecture: x64

        - name: Test Open Source Dependencies with Snyk
          uses: snyk/actions/java@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            command: test
            args: --all-projects